### ISSUE TITLE
Помогите барану!

### ISSUE THREAD

**Issue by ghost** [ru-doc/java-sdk#1]
Подскажите пожалуйста, никак не могу понять, что делать со всеми этими файлами? Очень хочется русскую документацию для IDE или в веб-формате, но здесь нет никаких инструкций :(

**Comment by blacky0x0** [comment]
Это исходники из JDK. Несколько пакетов переведены, а остальные выложены как заготовки к переводу. Переводов API и Tutorials практически нет. Есть старые переводы на javable.com  и на других ресурсах.
